#%RAML 1.0 Library

types:
    customerType:
        properties:
            firstname:
                type: string
                required: true
            lastname:
                type: string
                required: true
            age:
                type: integer
            address: 
                type: addressType
                required: true
            phone?:
                type: phoneType[]
    

    addressType:
        properties:
            street:
                type: string
                required: true
            city:
                type: string
                required: true
    
    phoneType: 
        properties:
            phoneNumber:
                type: string
            phoneType:
                enum:
                    - Mobile
                    - Phone